# Generated by Django 5.0.1 on 2024-02-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Emotion',
        ),
    ]
